<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="middleware-XPS-8300" name="org.genericsystem.example.TreesUses" tests="1" failures="1" timestamp="30 Jan 2015 15:15:00 GMT" time="0.258" errors="0">
  <testcase name="traverseTree" time="0.258" classname="org.genericsystem.example.TreesUses">
    <failure type="org.genericsystem.api.exception.RollbackException" message="org.genericsystem.api.exception.AliveConstraintViolationException: Your mutable is not still available">
      <![CDATA[org.genericsystem.api.exception.RollbackException: org.genericsystem.api.exception.AliveConstraintViolationException: Your mutable is not still available
	at org.genericsystem.cache.Cache.discardWithException(Cache.java:199)
	at org.genericsystem.mutability.Cache.unwrap(Cache.java:114)
	at org.genericsystem.mutability.Cache$$Lambda$71/198761306.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.genericsystem.mutability.Cache.unwrap(Cache.java:203)
	at org.genericsystem.mutability.Cache$2.addInstance(Cache.java:66)
	at org.genericsystem.mutability.Cache$2.addInstance(Cache.java:1)
	at org.genericsystem.api.defaults.DefaultVertex.addInstance(DefaultVertex.java:19)
	at org.genericsystem.api.defaults.DefaultVertex.addInstance(DefaultVertex.java:1)
	at org.genericsystem.api.defaults.DefaultWritable.addInstance(DefaultWritable.java:55)
	at org.genericsystem.api.defaults.DefaultWritable.addInstance(DefaultWritable.java:1)
	at org.genericsystem.api.defaults.DefaultTree.addRoot(DefaultTree.java:13)
	at org.genericsystem.example.TreesUses.traverseTree(TreesUses.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.genericsystem.api.exception.AliveConstraintViolationException: Your mutable is not still available
	... 42 more
]]>
    </failure>
  </testcase> <!-- traverseTree -->
</testsuite> <!-- org.genericsystem.example.TreesUses -->
